name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  arkworks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal -c rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --release --features bls12381_arkworks,bn254_arkworks
        
  blstrs_arkworks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal -c rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --release --features bls12381_blstrs,bn254_arkworks
